<a href="https://colab.research.google.com/github/Christian-Young/AI-Machine-Learning/blob/master/HW_4/HW4_Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 1

Using only `numpy`, implement the function `conv2d`. It takes as input `input_mat` and `kernel_mat` and outputs `output_mat`. All variables are square matrices. It should compute the convolution of `input_mat` with the kernel `kernel_mat` using valid padding.

Note that the size `s` of the kernel matrix can also be an even number.

In [0]:
# Imports.
import numpy as np

In [0]:
def conv2d(input_mat, kernel_mat):
  # The custom exception for when the input is invalid.
  if (kernel_mat.shape[0] > input_mat.shape[0]):
    raise Exception('Error: Kernal input is larger than input_mat.')
  
  # n is the input matrix tuple - w + 1.
  w = kernel_mat.shape[0]
  n = input_mat.shape[0] - kernel_mat.shape[0] + 1
  mat = np.zeros((n, n))

  for i in np.arange(n):
    for k in np.arange(n):
      for j in np.arange(w):
        for p in np.arange(w):
          mat[i][k] += kernel_mat[j][p] * input_mat[i + j][k + p]

  return mat

In [0]:
# Test cases. These are the test cases provided by Dr. Wocjan.
# I've already uncommented the test case for student testing
# and commented the other line.

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])


for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  # if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    # output_mat = []
  # else:
    # output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!



Exception: ignored