<a href="https://colab.research.google.com/github/Christian-Young/AI-Machine-Learning/blob/master/HW_4/HW4_Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 2

Using only `numpy`, implement the function `maxpooling2d`. It takes as input `input_mat` and `s` and outputs `output_mat`. The variables `input_mat` and `output_mat` are square matrices and `s` is an integer. It should compute the maxpooling operation on `input_mat` using window of shape `s` times `s`.

Make sure that you throw appropriate custom exceptions indicating the problem when the operations in Problem 1 and Problem 2 cannot be performed.

The test cases are in [test_cases_for_problems_1_2_homework_4](https://colab.research.google.com/drive/1MIoNq4_xglLesBF1kdWJelP2CmdPuYbv).

In [0]:
# Imports.
import numpy as np
import skimage.measure

In [0]:
def maxpooling2d(input_mat, s):
  # The custom exception for when the input is invalid.
  if (s > input_mat.shape[0]):
    raise Exception('Error: s is larger than input_mat.')
  
  # w / stride is the new size
  w = input_mat.shape[0]
  n = int(w / s)
  mat = np.zeros((n, n))

  for i in np.arange(n):
    for k in np.arange(n):
      mat[i][k] = input_mat[i * s][k * s]
      for j in np.arange(s):
        for p in np.arange(s):
          mat[i][k] = max(mat[i][k], input_mat[j + (i * s)][p + (k * s)])
  
  return mat

In [0]:
# Test cases. These are the testcases provided by Dr. Wocjan.
# I've already uncommented the test case for student testing
# and commented the other line.

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
